version: '3.8'

services:
  app:
    image: "${IMAGE_NAME}:latest" 
    container_name: bin_iot_app
    ports:
      - "8090:8080" 
    environment:
      - ENVIRONMENT=development
    volumes:
      - .:/app
    networks:
      - bin_iot_network
    command: sh -c "sleep 600" 
networks:
  bin_iot_network:
    driver: bridge
